Table User {
  userId integer [pk, unique]
  userNick varchar [not null, unique]
  userPw varchar [not null]
  userName varchar [not null]
  userPhone varchar [not null, unique]
  userEmail varchar
  userBirth datetime
  accId integer [unique, ref: > Account.accId]
  userImg integer [ref: > Image.imgId]
  regAt timestamp
  uptAt timestamp
  delAt timestamp
}

Table Address {
  addrId integer [pk, unique]
  userId integer [ref: > User.userId]
  addrRoad varchar [not null]
  addrDetl varchar [not null]
  addrZip varchar [not null]
  addrNick varchar
  isDef bool [default: false]
}

Table Friend {
  userId integer [pk, ref: > User.userId]
  frdId integer [pk, ref: > User.userId]
  status bit
  regAt timestamp
}

Table Funding {
  fundId integer [pk, unique]
  fundUuid varchar [unique]
  fundUser integer [ref: > User.userId]
  fundTitle varchar [not null]
  fundCont varchar [not null]
  fundTheme enum [not null]
  fundPubl bool [default: true]
  fundGoal integer [not null]
  fundSum integer [default: 0]
  fundAddr integer [not null, ref: > Address.addrId]
  endAt timestamp [not null]
  regAt timestamp
  uptAt timestamp
  delAt timestamp
}

Table Comment {
  comId integer [pk]
  fundId integer [not null, ref: > Funding.fundId]
  authorId integer [not null, ref: > User.userId]
  content varchar [not null]
  regAt timestamp
  isMod bool [not null, default: false]
  isDel bool [not null, default: false]
}

Table Gift {
  giftId integer [pk, unique]
  fundId integer [ref: > Funding.fundId]
  giftUrl varchar [not null]
  giftCrd integer [not null]
  giftOpt varchar
  giftCont varchar
}

Table Donation {
  donId integer [pk, unique]
  fundId integer [ref: > Funding.fundId]
  userId integer [ref: > User.userId]
  donStat enum [not null]
  orderId varchar [not null, unique] // 비회원이 후원한 경우 주문번호(order id)를 통해서 자신의 후원 정보를 볼 수 있어야 하기 때문.
  donAmnt integer [not null]
  regAt timestamp
}

Table RollingPaper {
  rollId integer [pk, ref: - Donation.donId]
  rollImg integer [ref: > Image.imgId]
  rollMsg varchar [default: '축하해요']
}

Table Notification {
  notiId integer [pk]
  recvId integer [not null, ref: > User.userId]
  sendId integer [not null, ref: > User.userId]
  notiType enum [not null]
  reqType enum [not null]
  subId integer
  notiTime timestamp
}

Table News {
  newsId integer [pk]
  userId integer [not null, ref: > User.userId]
  newsType enum [not null]
  newsTime timestamp
}

Table Gratitude {
  gratId integer [pk, ref: - Funding.fundId]
  gratTitle varchar [not null]
  gratCont varchar [not null]
  regAt timestamp
  isDel bool [default: false]
}

Table Image {
  imgId integer [pk, not null]
  imgUrl varchar [not null]
  imgType enum
  subId integer 
}

Table Account {
  accId integer [pk, not null]
  bank  enum [not null]
  accNum string [not null]
}

Enum FundTheme {
  Birthday
  Anniversary
  Donation
}

Enum DonationStatus {
  Donated
  WaitingRefund
  RefundComplete
}

Enum NotiType {
  IncomingFollow // 들어오는 친구 요청
  AcceptFollow // 내 요청에 대한 친구의 수락
  SatisfyingMyFunding //내 펀딩 달성
  DueDonatedFunding //내가 후원한 펀딩 마감
  WriteGratitude //감사 인사 작성 권유
  CheckGratitude //내가 후원한 펀딩 감사인사 확인
  IncomingDonation //내 펀딩에 들어온 새로운 후원
}

Enum NotiType {
    IncomingFollow // = 'IncomingFollow' 들어오는 친구 요청
    AcceptFollow // = 'AcceptFollow' 내 요청에 대한 친구의 수락
    FundClose // = 'FundClose' 내 펀딩 마감 
    FundAchieve // = 'FundAchieve' 내 펀딩 달성
    NewDonate // = 'NewDonate' 내 펀딩에 들어온 새로운 후원
    DonatedFundClose // = 'DonatedFundClose' 내가 후원한 펀딩 마감
    WriteGratitude // = 'WriteGratitude' 감사인사 작성 권유
    CheckGratitude // = 'CheckGratitude' 내가 후원한 펀딩 감사인사 확인
}

Enum NewsType {
  NewFunding // 친구의 새로운 펀딩 개설
  DueFunding // 친구의 펀딩 마감기한 임박
  Gratitude // 친구의 펀딩 감사인사
}

Enum ImgType {
  Gratitude
  Gift
  Funding
  User
  RollingPaper
}

Enum BankType {
  Kakaobank  // 카카오뱅크
  Nonghyup  // 농협
  Kookmin  // 국민은행
  Shinhan  // 신한은행
  Woori  // 우리은행
  Ibk  // IBK기업은행
  Hana  // 하나은행
  Daegu  // 대구은행
  Kyongnam  // 경남은행
  Gwangju  // 광주은행
  Busan  // 부산은행
  Jeju  // 제주은행
  Deutschebank  // 도이치은행
  Kdb  // KDB은행
  Nfcf  // 산림조합
  Kfcc  // 새마을금고
  Suhyup  // 수협
  Nacufok // 신협
  Citybank // 씨티은행
  Tossbank  // 토스뱅크
  Scbank  // SC제일은행
  Kbank  // 케이뱅
}

Enum ReqType {
  NotResponse // 00 // 요청에 응답하지 않은 상태
  Accept // 01 // 요청을 수락한 상태
  Refuse // 02 // 요청을 거절한 상태
  UnWritten // 03 // 감사인사를 작성하지 않은 상태
  Written // 04 // 감사인사를 작성한 상태
}
